# Ruff config for linting and formatting
line-length = 130

[lint]
select = [
    "I",   # isort
    "N",   # pep8-naming
    "F",   # pyflakes - flake8
    "E",   # pycodesytle - flake8
    "C90", # mccabe - flake8
    "D",   # pydocstyle - flake8-docstring
]
ignore = ["D104", "D105", "D107", "D206", "D401", "E501"]

isort.combine-as-imports = true
isort.known-first-party = []
isort.known-local-folder = []

pep8-naming.classmethod-decorators = ["classmethod", "root_validator", "validator"]

per-file-ignores."database/versions/*.py" = ["D103"]
per-file-ignores."**/tests/**/test_*.py" = ["D100", "D101", "D102", "D103"]
per-file-ignores."test/**/*.py" = ["D100"]

pydocstyle.convention = "pep257"