# Ruff config for linting and formatting
line-length = 130

[lint]
select = [
    "I",   # isort
    "N",   # pep8-naming
    "F",   # pyflakes - flake8
    "E",   # pycodesytle - flake8
    "W",   # pycodesytle warnings - flake8
    "C90", # mccabe - flake8
    "D",   # pydocstyle - flake8-docstring
    "B",   # flake8-bugbear
    "F",   # flake8 built-in checks
    "T10", # flake8-type-checking
    "RUF", # ruff built-in checks
    "C4",  # flake8-comprehensions
]
ignore = ["D104", "D105", "D107"]

isort.combine-as-imports = true
isort.known-first-party = []
isort.known-local-folder = ["stock_trader", "tests"]

pep8-naming.classmethod-decorators = ["classmethod", "root_validator", "validator"]

pydocstyle.convention = "google"