[mypy]
python_version=3.13

# Type checking
disallow_any_explicit = false
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = false
warn_unreachable = true
strict_equality = true

# Output
show_error_codes = true
color_output = true
error_summary = true
# pretty = true

plugins = pydantic.mypy, sqlalchemy.ext.mypy.plugin

# Ignore missing imports
[mypy-stock_trader.infrastructure.redis_client]
disable_error_code = misc


# Ignore missing imports for third-party libraries

[mypy-sqlalchemy_utils.*]
ignore_missing_imports = true

[mypy-celery.*]
ignore_missing_imports = true

[mypy-kombu.*]
ignore_missing_imports = true
