{{- if .Values.fetchWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stock-trader.fullname" . }}-fetch-worker
  labels:
    {{- include "stock-trader.labels" . | nindent 4 }}
    {{- include "stock-trader.selectorLabels" (dict "context" . "component" "fetch-worker") | nindent 4 }}
spec:
  replicas: {{ .Values.fetchWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "stock-trader.selectorLabels" (dict "context" . "component" "fetch-worker") | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.fetchWorker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "stock-trader.labels" . | nindent 8 }}
        {{- include "stock-trader.selectorLabels" (dict "context" . "component" "fetch-worker") | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: fetch-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.fetchWorker.command | nindent 12 }}
          envFrom:
            {{- include "stock-trader.envFrom" . | nindent 12 }}
          resources:
            {{- toYaml .Values.fetchWorker.resources | nindent 12 }}
      {{- with .Values.fetchWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fetchWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fetchWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
