apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stock-trader.fullname" . }}-secret
  labels:
    {{- include "stock-trader.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  MASSIVE_API_KEY: {{ .Values.secrets.massiveApiKey | quote }}
