"""Initial market data table.

Revision ID: 4b19bd66b772
Revises: bcdd27605b96
Created Date: 2026-02-17 02:45:28.169238

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Revision identifiers
revision: str = "4b19bd66b772"
down_revision: str | Sequence[str] | None = "bcdd27605b96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_data",
        sa.Column("uuid", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column(
            "interval",
            sa.Enum(
                "ONE_MINUTE",
                "FIVE_MINUTE",
                "FIFTEEN_MINUTE",
                "THIRTY_MINUTE",
                "ONE_HOUR",
                "DAILY",
                name="interval_enum",
                schema="stock_trader",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.Column("timestamp", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("volume", sa.BIGINT(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("symbol", "interval", "timestamp", name="uq_market_data_symbol_interval_timestamp"),
        schema="stock_trader",
    )
    op.create_index(
        "ix_market_data_symbol_interval_ts",
        "market_data",
        ["symbol", "interval", "timestamp"],
        unique=False,
        schema="stock_trader",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_market_data_symbol_interval_ts", table_name="market_data", schema="stock_trader")
    op.drop_table("market_data", schema="stock_trader")
    # ### end Alembic commands ###
