"""Change type.

Revision ID: b3ad9bd1b1d3
Revises: 8bb6b5de95e4
Created Date: 2026-02-18 04:08:03.481779

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers
revision: str = "b3ad9bd1b1d3"
down_revision: str | Sequence[str] | None = "8bb6b5de95e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "backtest_jobs",
        "error",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.TEXT(),
        existing_nullable=True,
        schema="stock_trader",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "backtest_jobs",
        "error",
        existing_type=sa.TEXT(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
        schema="stock_trader",
    )
    # ### end Alembic commands ###
