"""Add date.

Revision ID: 8bb6b5de95e4
Revises: 4b19bd66b772
Created Date: 2026-02-17 04:55:45.323310

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers
revision: str = "8bb6b5de95e4"
down_revision: str | Sequence[str] | None = "4b19bd66b772"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("backtest_jobs", sa.Column("start_date", sa.Date(), nullable=False), schema="stock_trader")
    op.add_column("backtest_jobs", sa.Column("end_date", sa.Date(), nullable=False), schema="stock_trader")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("backtest_jobs", "end_date", schema="stock_trader")
    op.drop_column("backtest_jobs", "start_date", schema="stock_trader")
    # ### end Alembic commands ###
