"""Create initial tables.

Revision ID: 0a8496d67f2d
Revises: 0d583eb2b2f7
Created Date: 2026-01-19 21:53:32.461356

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Revision identifiers
revision: str = "0a8496d67f2d"
down_revision: str | Sequence[str] | None = "0d583eb2b2f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_jobs",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="backtest_job_status",
                schema="stock_trader",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.Column("strategy_name", sa.String(length=50), nullable=False),
        sa.Column("symbols", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.String(length=255), nullable=True),
        sa.Column("create_time", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("start_time", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("end_time", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        schema="stock_trader",
    )
    op.create_index("ix_backtest_jobs_created", "backtest_jobs", ["create_time"], unique=False, schema="stock_trader")
    op.create_index("ix_backtest_jobs_status", "backtest_jobs", ["status"], unique=False, schema="stock_trader")
    op.create_table(
        "backtest_results",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("create_time", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["stock_trader.backtest_jobs.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("job_id", name="uq_backtest_results_job_id"),
        schema="stock_trader",
    )
    op.create_table(
        "job_events",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("event", sa.TEXT(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("create_time", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["stock_trader.backtest_jobs.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        schema="stock_trader",
    )
    op.create_index("ix_job_events_job_id_created", "job_events", ["job_id", "create_time"], unique=False, schema="stock_trader")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_events_job_id_created", table_name="job_events", schema="stock_trader")
    op.drop_table("job_events", schema="stock_trader")
    op.drop_table("backtest_results", schema="stock_trader")
    op.drop_index("ix_backtest_jobs_status", table_name="backtest_jobs", schema="stock_trader")
    op.drop_index("ix_backtest_jobs_created", table_name="backtest_jobs", schema="stock_trader")
    op.drop_table("backtest_jobs", schema="stock_trader")
    # ### end Alembic commands ###
